### ISSUE TITLE
TLS Handshake failed for Azure SQL Server on an azure VM

### ISSUE THREAD

**Issue by zhongyi-zhang** [denisenkom/go-mssqldb#288] opened 2017-09-05 05:23 UTC
The format of my connection string:
```
sqlserver://<username>:<password>@<servername>.database.windows.net:1433?TrustServerCertificate=false&database=master&encrypt=true&hostNameInCertificate=%2A.database.windows.net
```

It works on my local machine. But It just fails on an Azure VM, with following error message:
```
TLS Handshake failed: x509: certificate is valid for tr34.eastus1-a.worker.database.windows.net, *.tr34.eastus1-a.worker.database.windows.net, not *.database.windows.net
```

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-architecture
I think this issue is caused by the different connection policies between inside Azure machines and outside Azure machines.

**Comment by AbelHu** [comment] 2017-09-13 05:33
Could go-mssqldb support to use a custom server name with TLS, just like [mysql](https://godoc.org/github.com/go-sql-driver/mysql#RegisterTLSConfig)?

**Comment by blacksails** [comment] 2017-09-24 19:21
I have the exact same issue

**Comment by kardianos** [comment] 2017-09-24 20:22
I don't think this is a driver issue. (though Please point to how it might be). It sounds like a certificate mismatch to me. I can connect to a azure SQL Server instance without the trust Server Certificate line. Can you diagnose more?

**Comment by zhongyi-zhang** [comment] 2017-09-25 02:18
@kardianos 
It still failed unless also removing the option "encrypt=true".

As the README.md says:
* "TrustServerCertificate" 
  * false - Server certificate is checked. Default is false if encypt is specified.
  * true - Server certificate is not checked. Default is true if encrypt is not specified. If trust server certificate is true, driver accepts any certificate presented by the server and any host name in that certificate. In this mode, TLS is susceptible to man-in-the-middle attacks. **This should be used only for testing.**

It is not secure to remove them, right?

**Comment by blacksails** [comment] 2017-09-25 08:49
I tried connecting with a JDBC driver from another language with the same options, and that just works without a problem.

**Comment by AbelHu** [comment] 2017-09-25 09:13
@blacksails It seems like that [some special code](https://github.com/Microsoft/mssql-jdbc/blob/24dfd491e047d564c3c247f66f381d72460e17bb/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L3612-L3640) was added in mssql-jdbc to handle the rerouted subdomain.

**Comment by blacksails** [comment] 2017-09-25 09:44
@AbelHu lol that seems a bit hacky imo.

**Comment by kardianos** [comment] 2017-09-25 14:48
Here is the DSN I use to connect to Azure. Could you try it out?
```
sqlserver://<user>:<password>@<instance>.database.windows.net:1433?encrypt=true&database=<db>
```

**Comment by zhongyi-zhang** [comment] 2017-09-26 02:04
Yes. I tried this one. It succeeded on my local machine and failed on an Azure VM. I've requested support from Azure SQL team. Maybe they'll do some changes in the backend or contribute codes similar to what @AbelHu mentioned to this repo.

**Comment by blacksails** [comment] 2017-09-26 14:25
@zhongyi-zhang Please share the info azure provides, when they get back to you.

**Comment by janivihervas** [comment] 2017-10-05 08:15
I had the same issue but using

sqlserver://{user}:{password}@{instance}.database.**secure**.windows.net:1433?database={db}&encrypt=true&connection+timeout=30

as a connection string solved it.

**Comment by zhongyi-zhang** [comment] 2017-10-09 05:53
"{instance}.database**.secure**.windows.net" works for me, too.
And I asked Azure support for suggestion.
The following is what the engineer replied to me:
> "{instance}.database.secure.windows.net" is used for **downlevel** clients to connect to the database with **Table Auditing** enabled, you can refer to the document below for more details: https://docs.microsoft.com/en-us/azure/sql-database/sql-database-auditing-and-dynamic-data-masking-downlevel-clients

> For the SQL clients that support TDS redirection, the redirection works automatically. 

> Kindly notice: Since Table Auditing is now deprecated, it’s not required to use this connection string for downlevel client by using the new **Blob Auditing** method. So there is no necessary to use it anymore 

In short, it is deprecated and not recommended.
What they recommend is still changing the connection policy to "proxy".

**Comment by tevert** [comment] 2018-02-06 19:47
Same behavior here - we're integrating Hashicorp's vault with our Azure SQL instances, and we can't encrypt the connection without using the `*.database.secure.windows.net` address.

**Comment by kardianos** [comment] 2018-10-27 05:29
There has been a fix that connecting to Azure on time in this time frame. I'm going to assume this is related and close it. If this is still an issue, please create a new issue or re-open this one.

**Closed by kardianos** 2018-10-27 05:29 UTC

**Comment by Timer** [comment] 2019-01-23 04:57
I just experienced this now, was anyone aware of the final resolution?

```
returned a non-nil error: TLS Handshake failed: x509: certificate is valid for tr30.eastus1-a.worker.database.windows.net, *.tr30.eastus1-a.worker.database.windows.net, *.hs1.tr30.eastus1-a.worker.database.windows.net, *.hs2.tr30.eastus1-a.worker.database.windows.net, *.hs3.tr30.eastus1-a.worker.database.windows.net, not foo-bar.database.windows.net
```

**Comment by techjacker** [comment] 2019-06-10 12:18
@Timer I'm having the same issue

**Comment by v-kaywon** [comment] 2019-06-13 16:17
@techjacker may I ask you for the repro steps? What is the connection string you are using? Are you able to connect to Azure via other methods (e.g., SSMS)?

**Comment by techjacker** [comment] 2019-06-14 15:30
This is the connection string: 
```
fmt.Sprintf(`sqlserver://%s:%s@%s:%d?database=%s&encrypt=%s&trustServerCertificate=false`,
		c.UserName,
		c.Password,
		c.Host,
		c.Port,
		c.Name,
		c.Encrypt,
	)
```

When I run inside a docker container from my local machine it connects to the azure DB fine but when I run on our kubernetes cluster it returns at TLS error. I tried adding `&hostNameInCertificate=*.database.windows.net` to the end of the connection string but still get this error:
```
"TLS Handshake failed: x509: certificate is valid for tr19.westeurope1-a.worker.database.windows.net, *.tr19.westeurope1-a.worker.database.windows.net, *.hs1.tr19.westeurope1-a.worker.database.windows.net, *.hs2.tr19.westeurope1-a.worker.database.windows.net, *.hs3.tr19.westeurope1-a.worker.database.windows.net, not *.database.windows.net"
```

We're able to connect from kubernetes if we change the DB [connection](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-architecture#connection-policy) policy to `Proxy` but this is not ideal.

The cluster worker nodes are running RHEL. I managed to spin up a python container in the RHEL box and connect via `mssql-cli` but the golang alpine container always fails (and yes the dockerfile does install the certificates via `RUN apk --no-cache add ca-certificates`). The fact that is works from my laptop makes me think it is something to do with the RHEL host.

**Comment by v-kaywon** [comment] 2019-06-17 22:38
@techjacker I was doing some more digging, looks like redirect mode is not supported by the driver at this point (see #282 and [Azure SQL Connectivity Architecture](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-architecture).) I don't think it has to do with RHEL host; the reason why it works for your local machine is likely because the connection policy is set to Proxy.

**Comment by techjacker** [comment] 2019-06-18 17:03
@v-kaywon I'm pretty sure I had the connection policy set to default when I was testing locally but I might be wrong.

Are there any plans to add support for redirect connections to the driver?

**Comment by v-kaywon** [comment] 2019-07-06 00:22
Can you try the fix in PR #488 ?

**Comment by techjacker** [comment] 2019-07-11 15:46
@v-kaywon I tried the fix but unfortunately it didn't solve the problem.

**Comment by v-kaywon** [comment] 2019-07-11 16:00
@techjacker are you getting the same error message as before?

```
"TLS Handshake failed: x509: certificate is valid for tr19.westeurope1-a.worker.database.windows.net, *.tr19.westeurope1-a.worker.database.windows.net, *.hs1.tr19.westeurope1-a.worker.database.windows.net, *.hs2.tr19.westeurope1-a.worker.database.windows.net, *.hs3.tr19.westeurope1-a.worker.database.windows.net, not *.database.windows.net"
```

Also in your connection string, what are the Encrypt and the TrustServerCertificate properties set to?

**Comment by techjacker** [comment] 2019-07-11 16:01
the same error message:
```{"_source":"server/server.go:41","message":"Error creating MSSQL connection: TLS Handshake failed: x509: certificate is valid for management.westeurope1-a.control.database.windows.net, management.westeurope.control.database.windows.net, *.database.windows.net, *.database.s
secure.windows.net, *.secondary.database.windows.net, admin.westeurope1-a.control.database.windows.net, *.westeurope1-a.control.database.windows.net, westeurope1-a.control.database.windows.net, *.provisioning.database.windows.net, not true","severity":"fatal","time":"20190-07-11T15:42:28.468266178Z","timestamp":"2019-07-11T15:42:28.468242978Z"}```

**Comment by techjacker** [comment] 2019-07-11 16:02
I added `&hostnameincertificate=true` to the DB connection string

**Comment by v-kaywon** [comment] 2019-07-11 16:10
`hostnameincertificate` is the host name used for certificate validation, it is not a Boolean property. Can you try to remove it from the connection string.

**Comment by techjacker** [comment] 2019-07-11 16:20
yes I tried the first time without it and had the same error

**Comment by v-kaywon** [comment] 2019-07-11 16:22
Can you post the error message with `hostnameincertificate` removed from the connection string?

**Comment by techjacker** [comment] 2019-07-11 16:24
it was the same

```{"_source":"server/server.go:41","message":"Error creating MSSQL connection: TLS Handshake failed: x509: certificate is valid for tr15.westeurope1-a.worker.database.windows.net, *.tr15.westeurope1-a.worker.database.windows.net, *.hs1.tr15.westeurope1-a.worker.database.win
dows.net, *.hs2.tr15.westeurope1-a.worker.database.windows.net, *.hs3.tr15.westeurope1-a.worker.database.windows.net, not mango-dev-sql-server.database.windows.net","severity":"fatal","time":"2019-07-11T14:39:04.592286443Z","timestamp":"2019-07-11T14:39:04.592244043Z"}```

**Comment by v-kaywon** [comment] 2019-07-11 16:25
What is the server name you're trying to connect to?

**Comment by techjacker** [comment] 2019-07-11 16:27
`mango-dev-sql-server.database.windows.net`

**Comment by v-kaywon** [comment] 2019-07-11 16:36
With the fix, the `hostnameincertificate` should be internally updated to the rerouted host name. From the error message that you posted, looks like it is not updated, which is the old behaviour. Can you make sure you have the latest driver?

**Comment by techjacker** [comment] 2019-07-11 16:46
yes I updated the driver before running it

**Comment by v-kaywon** [comment] 2019-07-11 17:25
When did you update the driver? The fix was not merged until 2 days ago.

**Comment by techjacker** [comment] 2019-07-11 17:26
a couple of hours ago

**Comment by v-kaywon** [comment] 2019-07-11 17:41
OK, I'm not sure why the error still persist. Can you do the following for me please?
1. Share your connection string. I want to make sure the properties are set correctly.
2. Since the driver is not versioned, It's hard to check if you have the right version of the driver. Can you go to `%GOPATH%\src\github.com\denisenkom\go-mssqldb\tds.go` line 1054 and make sure the code is
```
if ok {
	p.hostInCertificateProvided = true
} else {
	p.hostInCertificate = p.host
	p.hostInCertificateProvided = false
}
```
If the code is not as above, you have an older version of the driver, and it needs to be updated. If the code is the same as above, please try to run `go build` and `go install` to rebuild the driver.

**Comment by techjacker** [comment] 2019-07-11 17:46
This is from our `go.mod`:
```
	github.com/denisenkom/go-mssqldb v0.0.0-20190710001350-29e7b2419f38
```
which is the latest with your merged changes.

I deployed through our CI which rebuilds a docker image on every commit so definitely has the latest code.

The connection string is this:

```
	return fmt.Sprintf(`sqlserver://%s:%s@%s:%d?database=%s&encrypt=%s&trustServerCertificate=false`,
		c.UserName,
		c.Password,
		c.Host,
		c.Port,
		c.Name,
		c.Encrypt,
	)
```

**Comment by v-kaywon** [comment] 2019-07-11 21:57
I tried again with connection mode redirect, but I'm unable to reproduce the issue. Since the server you're trying to connect to and the host name reported in the error are the same, it must mean the hostnameincertificate is not updated with the routed server. Could you add the following 2 lines after https://github.com/denisenkom/go-mssqldb/blob/master/tds.go#L1371 in the code so I can see what the hostnameincerficate and routedserver are?

```
log.Println("routedServer:", sess.routedServer)
log.Println("hostInCertificate:", p.hostInCertificate)
```
