### ISSUE TITLE
Support returning multiple errors

### ISSUE THREAD

**Issue by sjjian** [denisenkom/go-mssqldb#442] opened 2019-01-21 10:07 UTC
Hi guys,
when I using the driver to execute SQL query, SQL like: 
```sql
CREATE TABLE test(id bigint unsigned auto_increment, CONSTRAINT PK_test_pk PRIMARY KEY(id))
```
1. if constraint "PK_test_pk“ is exists，result from sqlcmd（**i want**）: 
``` bash
Msg 2714, Level 16, State 5, Server 73b6ed4d3e68, Line 1
There is already an object named 'PK_test_pk' in the database.
Msg 1750, Level 16, State 1, Server 73b6ed4d3e68, Line 1
Could not create constraint or index. See previous errors.
```
2. but i just get result from driver:
``` bash
Could not create constraint or index. See previous errors.
````
3. this is debug log:
``` bash
2019/01/21 17:30:41 initiating response reading
2019/01/21 17:30:41 got token tokenError
2019/01/21 17:30:41 got ERROR 2714 There is already an object named 'PK_test_pk' in the database.
2019/01/21 17:30:41 got token tokenError
2019/01/21 17:30:41 got ERROR 1750 Could not create constraint or index. See previous errors.
2019/01/21 17:30:41 got token tokenDone
2019/01/21 17:30:41 got DONE or DONEPROC status=2
2019/01/21 17:30:41 response finished
```
Can you support returning all error messages? thanks!

**Comment by abheyshah** [comment] 2019-01-23 09:58
My work around for this issue is to use IF @@ERROR = 0 after each statement.

**Comment by sjjian** [comment] 2019-01-31 05:47
@abheyshah oh thanks, but i can't modify the statement.

**Comment by kardianos** [comment] 2019-02-05 00:32
Duplicate of #39 .

**Closed by kardianos** 2019-02-05 00:32 UTC

**Comment by flibustenet** [comment] 2020-05-12 13:40
@abheyshah could you give an example with your workaround ?

**Comment by abheyshah** [comment] 2020-05-13 13:11
Not got the relevant code to hand but  the intent is that you do some error
handling as part of the sql statement, such that you only return a single
error message instead of multiple messages that the driver won't pass on to
you..
https://docs.microsoft.com/en-us/sql/t-sql/functions/error-transact-sql?view=sql-server-ver15
good luck

**Comment by sjjian** [comment] 2020-05-13 14:02
@flibustenet 
```go
type doneStruct struct {
	Status   uint16
	CurCmd   uint16
	RowCount uint64
	errors   []Error
}

func (d doneStruct) isError() bool {
	return d.Status&doneError != 0 || len(d.errors) > 0
}

func (d doneStruct) getError() Error {
	if len(d.errors) > 0 {
		return d.errors[len(d.errors)-1]
	} else {
		return Error{Message: "Request failed but didn't provide reason"}
	}
}
```
hello，the problem is doneStruct.getError just return first error message, i think.
