### ISSUE TITLE
SSPI authentication error when connecting to local instance

### ISSUE THREAD

**Issue by SQLServerIO** [denisenkom/go-mssqldb#163] opened 2016-08-11 02:18 UTC
Ok,
After hours of debugging #162 it isn't just a IPv6 issue. 

It actually throws an authentication error with SSPI if you use a string for the server part of the connection string.

If you try localhost, servername or servername.domain.local none of it works. If you use 127.0.0.1 or the IPv4 address it connects just fine with SSPI.

I've tested this on:
SQL Server 2005 RTM / Windows 2008
SQL Server 2008 RTM / Windows 2008
SQL Server 2008 R2 RTM / Windows 2008 R2
SQL Server 2008 R2 SP1 / Windows 2008 R2
SQL Server 2008 R2 SP2 / Windows 2008 R2
SQL Server 2012 RTM / Windows 2012
SQL Server 2012 SP1 / Windows 2012 R2
SQL Server 2014 RTM / Windows 2012 R2
SQL Server 2016 RTM / Windows 2012 R2

The only one it works as expected on is SQL Server 2012 SP1 / Windows 2012 R2. I have no clue why at the moment.

**Comment by SQLServerIO** [comment] 2016-08-11 07:08
I got a clue, typeo on the command line with a default set made me think it was connecting to the local server it was not. It also shows the same problem as all the others.

I have checks SPN's for all machines as well all check out.

Looking at the logs I can see that when I connect via IPv4 it looks like it is actually using NTLM for both local and remote connections.

**Comment by clns** [comment] 2017-02-16 13:59
Not sure if this helps, but specifying the host machine as IP instead of hostname in the named instance works for me. Example:

Instead of this (which doesn't work):

```
COMPUTER-NAME\MSSQLSERVER01
```

I'm using this (which does work):

```
127.0.0.1\MSSQLSERVER01
```

**Comment by kardianos** [comment] 2018-10-27 05:50
Without exact steps used to reproduce this, it is difficult to understand what could be going wrong. But, here is a guess:

 * Windows auth on windows may resolve host names using non-DNS.
 * Go only understands hostname resolution by using DNS.
 * Maybe some mismatch here causes an odd failure mode.

I'm closing for now. Exact steps to reproduce would be useful.

**Closed by kardianos** 2018-10-27 05:50 UTC

**Comment by zbyndis** [comment] 2019-01-16 13:55
This is how to reproduce this issue using the [/examples/simple/simple.go](../blob/master/examples/simple/simple.go) when **running it directly on the server** with default SQL Server instance:

`simple.exe -server localhost`
or
`simple.exe -server <hostname>`

Error:
`Scan failed:failed to send SQL Batch: write tcp: wsasend: An existing connection was forcibly closed by the remote host.`

Workaround:
`simple.exe -server 127.0.0.1`
