### ISSUE TITLE
Consider returning an error in case of a bad connection string

### ISSUE THREAD

**Issue by tartale** [denisenkom/go-mssqldb#171] opened 2016-09-22 03:15 UTC
The following connection strings are illegal, but silently ignored:

`;;;`
`=foo; user id=bar; password=baz`

Since the `Open()` function allows returning of an error, it seems reasonable to report these as errors.

**Comment by denisenkom** [comment] 2016-12-08 03:58
Driver already returns error on bad connection string.  The issue is that sql.DB.Open does not call driver's Open method until query is made.  So I don't think this issue can be fixed on driver level.

**Closed by denisenkom** 2016-12-08 03:58 UTC

**Comment by kardianos** [comment] 2016-12-08 16:24
Users should always call DB.Ping after opening a db pool.
