### ISSUE TITLE
Not implemented panic in go 1.16

### ISSUE THREAD

**Issue by liorblob** [denisenkom/go-mssqldb#639] opened 2021-02-17 14:18 UTC
Got the following error when I tried to use `Ping` after upgrading go to 1.16:
```
panic: Not implemented [recovered]
	panic: Not implemented
goroutine 8 [running]:
testing.tRunner.func1.2(0xb2b8a0, 0xcd5480)
	/usr/local/go/src/testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc000102a80)
	/usr/local/go/src/testing/testing.go:1147 +0x4b6
panic(0xb2b8a0, 0xcd5480)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/denisenkom/go-mssqldb.timeoutConn.SetWriteDeadline(...)
	/builds/gopath/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20190820223206-44cdfe8d8ba9/net.go:102
crypto/tls.(*Conn).SetWriteDeadline(...)
	/usr/local/go/src/crypto/tls/conn.go:150
crypto/tls.(*Conn).closeNotify(0xc0000be000, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1360 +0xfd
crypto/tls.(*Conn).Close(0xc0000be000, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1330 +0xd7
github.com/denisenkom/go-mssqldb.(*Conn).Close(0xc000aae000, 0x0, 0x0)
	/builds/gopath/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20190820223206-44cdfe8d8ba9/mssql.go:361 +0x3a
database/sql.(*driverConn).finalClose.func2()
	/usr/local/go/src/database/sql/sql.go:592 +0x49
database/sql.withLock(0xce7670, 0xc0000e8000, 0xc0006f5918)
	/usr/local/go/src/database/sql/sql.go:3294 +0x69
database/sql.(*driverConn).finalClose(0xc0000e8000, 0x0, 0xc0006f5998)
	/usr/local/go/src/database/sql/sql.go:590 +0x13c
database/sql.(*driverConn).Close(0xc0000e8000, 0xc0000e8000, 0x0)
	/usr/local/go/src/database/sql/sql.go:571 +0x135
database/sql.(*DB).putConn(0xc0003a4f70, 0xc0000e8000, 0x0, 0x0, 0xce7601)
	/usr/local/go/src/database/sql/sql.go:1398 +0x2f7
database/sql.(*driverConn).releaseConn(...)
	/usr/local/go/src/database/sql/sql.go:475
database/sql.(*DB).pingDC(0xc0003a4f70, 0xcece50, 0xc0000460b0, 0xc0000e8000, 0xc0006f5b60, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:788 +0x84
database/sql.(*DB).PingContext(0xc0003a4f70, 0xcece50, 0xc0000460b0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:811 +0x185
database/sql.(*DB).Ping(...)
	/usr/local/go/src/database/sql/sql.go:817
```

Looking at the 1.16 release notes, this change might be the cause:
https://golang.org/doc/go1.16#crypto/tls
`A default write deadline is now set in Conn.Close before sending the "close notify" alert, in order to prevent blocking indefinitely.`
https://github.com/denisenkom/go-mssqldb/blob/045585d74f9069afe2e115b6235eb043c8047043/net.go#L61

**Comment by jpvillaseca** [comment] 2021-02-18 19:45
It also happened to me in Go 1.16, but when reverting to Go 1.15.6 the issue did not occur.

```
panic: Not implemented

goroutine 36 [running]:
github.com/denisenkom/go-mssqldb.passthroughConn.SetWriteDeadline(...)
	/go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.9.0/net.go:167
crypto/tls.(*Conn).SetWriteDeadline(...)
	/usr/local/go/src/crypto/tls/conn.go:150
crypto/tls.(*Conn).closeNotify(0xc000094000, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1360 +0xfd
crypto/tls.(*Conn).Close(0xc000094000, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1330 +0xd7
github.com/denisenkom/go-mssqldb.(*Conn).Close(0xc00009e500, 0x0, 0x0)
	/go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.9.0/mssql.go:361 +0x3a
database/sql.(*driverConn).finalClose.func2()
	/usr/local/go/src/database/sql/sql.go:592 +0x49
database/sql.withLock(0x116b6d0, 0xc0004a8120, 0xc000058670)
	/usr/local/go/src/database/sql/sql.go:3294 +0x69
database/sql.(*driverConn).finalClose(0xc0004a8120, 0xc000480000, 0xc000438808)
	/usr/local/go/src/database/sql/sql.go:590 +0x13c
database/sql.(*driverConn).Close(0xc0004a8120, 0xc00082c458, 0x1)
	/usr/local/go/src/database/sql/sql.go:571 +0x135
database/sql.(*DB).connectionCleaner(0xc0003e8410, 0xd18c2e2800)
	/usr/local/go/src/database/sql/sql.go:1022 +0x6d
created by database/sql.(*DB).startCleanerLocked
	/usr/local/go/src/database/sql/sql.go:992 +0xb7
```

Thank you @liorblob mentioning that it was related to 1.16, it helped me to prevent the issue in production.

**Comment by spetr** [comment] 2021-02-19 20:59
You can test fixed version with this go.mod modification (add row "replace"):

```
module .....
go 1.16

require (
 ....
)

replace github.com/denisenkom/go-mssqldb => github.com/spetr/go-mssqldb v0.9.1-0.20210219202709-e432f8ee7c66
```

**Comment by Woody1193** [comment] 2021-03-17 06:51
I had a similar issue when calling Close:

```
panic: Not implemented

goroutine 73 [running]:
github.com/denisenkom/go-mssqldb.passthroughConn.SetWriteDeadline(...)
        C:/Users/ryanw/Documents/go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20201105052611-0f236ab67f08/net.go:167
crypto/tls.(*Conn).SetWriteDeadline(...)
        C:/Program Files/Go/src/crypto/tls/conn.go:150
crypto/tls.(*Conn).closeNotify(0xc000da1880, 0x0, 0x0)
        C:/Program Files/Go/src/crypto/tls/conn.go:1360 +0x10d
crypto/tls.(*Conn).Close(0xc000da1880, 0x0, 0x0)
        C:/Program Files/Go/src/crypto/tls/conn.go:1330 +0xe5
github.com/denisenkom/go-mssqldb.(*Conn).Close(0xc000b22080, 0x0, 0x0)
        C:/Users/ryanw/Documents/go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20201105052611-0f236ab67f08/mssql.go:365 +0x42
database/sql.(*driverConn).finalClose.func2()
        C:/Program Files/Go/src/database/sql/sql.go:592 +0x50
database/sql.withLock(0x18e0c48, 0xc0000922d0, 0xc0005b16b0)
        C:/Program Files/Go/src/database/sql/sql.go:3294 +0x70
database/sql.(*driverConn).finalClose(0xc0000922d0, 0xc0005b1758, 0xf8a459)
        C:/Program Files/Go/src/database/sql/sql.go:590 +0x145
database/sql.(*driverConn).Close(0xc0000922d0, 0xc0000922d0, 0x0)
        C:/Program Files/Go/src/database/sql/sql.go:571 +0x135
database/sql.(*DB).putConn(0xc000bb6000, 0xc0000922d0, 0x0, 0x0, 0x1)
        C:/Program Files/Go/src/database/sql/sql.go:1398 +0x2f7
database/sql.(*driverConn).releaseConn(...)
        C:/Program Files/Go/src/database/sql/sql.go:475
database/sql.(*Conn).close(0xc000940180, 0x0, 0x0, 0x0, 0x0)
        C:/Program Files/Go/src/database/sql/sql.go:1998 +0xb9
database/sql.(*Conn).Close(...)
        C:/Program Files/Go/src/database/sql/sql.go:2010
```

**Comment by uvw** [comment] 2021-03-17 16:03
I've been running this PR https://github.com/denisenkom/go-mssqldb/pull/642 in non-production environments for a week now and haven't found any issues so far.

Not sure if the PR fixes the issue correctly or if something is missing. A review from the authors/maintainers would be great.

To switch to this fix, add `replace github.com/denisenkom/go-mssqldb => github.com/robinknaapen/go-mssqldb v0.9.1-0.20210310163057-81bf11eac854` to `go.mod`.

**Comment by lw-bmc** [comment] 2021-04-01 06:45
I've reported this in github.com/jmoiron/sqlx. I've included a reproducible scenario. When I build an application with Go 1.13, all works fine, but same app, built using 1.16.2 breaks.

https://github.com/jmoiron/sqlx/issues/719#issue-846843659

**Comment by jason-swissre** [comment] 2021-04-01 13:39
Hi

Has there been any movement on this?  My team is hitting this problem now too.

**Comment by atc0005** [comment] 2021-04-01 13:48
@dimdin , @kardianos - do either of you have review/merge privileges to this repo?

CC: @denisenkom

**Comment by dimdin** [comment] 2021-04-01 13:59
> 
> 
> @dimdin , @kardianos - do either of you have review/merge privileges to this repo?
> 
> CC: @denisenkom
I' ll try to have a fix for that. It must work with both new and old versions that don't have deadlines.

**Comment by Steiniche** [comment] 2021-04-06 16:59
Just tested this with golang 1.16 and the fix suggested by @uvw works.

**Comment by denisenkom** [comment] 2021-04-11 16:39
PR is merged, please check if there are no issues at this point

**Comment by atc0005** [comment] 2021-04-27 15:22
> PR is merged, please check if there are no issues at this point

FWIW, the new release is working for me.

**Comment by kardianos** [comment] 2021-09-23 16:35
Looks like this is fixed and a release has been issued. Closing.

**Closed by kardianos** 2021-09-23 16:35 UTC
