### ISSUE TITLE
go1.8: support for additional features

### ISSUE THREAD

**Issue by kardianos** [denisenkom/go-mssqldb#178] opened 2016-11-01 16:54 UTC
Many new important features will land in go1.8. Please see document:
https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit?usp=sharing for the full list.

Because these features are new we want drivers to implement them before they are released. Ideally they should be implemented by 2016-12-12 to allow for any driver provided feedback from implementation if necessary.

**Comment by kardianos** [comment] 2016-11-11 22:25
Are these changes of interest to the authors of this package? If so, which ones? Would PRs be considered?

**Comment by denisenkom** [comment] 2016-11-14 00:27
We are interested in those changes, PRs are welcome.  I, personally, may look into implementing "multiple record sets" feature.

**Comment by denisenkom** [comment] 2016-11-14 02:12
How can I get go1.8?  I cloned go repository and built from master branch but it does not seem to have new interfaces.  For example it complains: rows.HasNextResultSet undefined (type *sql.Rows has no field or method HasNextResultSet)

My go build reports this version:
go version devel +2f76c19 Mon Nov 14 00:24:27 2016 +0000 windows/amd64

I also can't find 1.8 branch:
  remotes/origin/HEAD -> origin/master
  remotes/origin/dev.cc
  remotes/origin/dev.garbage
  remotes/origin/dev.gcfe
  remotes/origin/dev.power64
  remotes/origin/dev.ssa
  remotes/origin/dev.tls
  remotes/origin/master
  remotes/origin/release-branch.go1
  remotes/origin/release-branch.go1.1
  remotes/origin/release-branch.go1.2
  remotes/origin/release-branch.go1.3
  remotes/origin/release-branch.go1.4
  remotes/origin/release-branch.go1.5
  remotes/origin/release-branch.go1.6
  remotes/origin/release-branch.go1.7
  remotes/origin/release-branch.r57
  remotes/origin/release-branch.r58
  remotes/origin/release-branch.r59
  remotes/origin/release-branch.r60

**Comment by kardianos** [comment] 2016-11-14 05:39
Look in the driver pkg. What does go doc say?

**Comment by denisenkom** [comment] 2016-11-20 04:17
Sorry, not sure where should I look.  I implemented stubs for RowsNextResultSet and RowsNextResultSet methods but I am trying to write a simple test to make sure those stubs are being called.

I believe the problem is that I am currently on go 1.7.  My go version is this: go version devel +2f76c19 Mon Nov 14 00:24:27 2016 +0000 windows/amd64

I cannot find instructions on how to get go 1.8 or how to test new functionality.

**Comment by kardianos** [comment] 2016-11-20 04:44
Do you have an existing patch you want to test? If so, just throw it on a branch on github and give me RW to it.
...
Here are the instructions to install from source:
https://golang.org/doc/install/source

You already have go installed, so no need to install go1.4, just set the `GOROOT_BOOTSTRAP` to your existing go install, maybe `C:\go` and then in your git cloned location (not the same path), run `src\all.bat`. Might need to set the new git\go\bin in the PATH rather then your C:\go\bin in the path.

**Comment by denisenkom** [comment] 2016-11-21 02:12
Ok, looks like I did follow correct build instructions.  I was confused because go repository did not have 1.8 branch in it.  I wan't sure that I was on a correct branch.  I looked at database/sql package in master branch and verified that it does have NextResultSet code in it.

I created new branch https://github.com/denisenkom/go-mssqldb/tree/nextresultset-denisenk, it contains stubs for NextResultSet methods and a test.  Also I gave you access to the repository.  Currently go test fails with following error message:
.\queries_test.go:725: rows.HasNextResultSet undefined (type *sql.Rows has no field or method HasNextResultSet)
FAIL    github.com/denisenkom/go-mssqldb [build failed]

I would appreciate your help with getting this branch to compile.  Once it successfully compiles and runs I would be able to replace stubs with actual implementation.

**Comment by kardianos** [comment] 2016-11-21 04:50
Sounds good. I'll take a look at it soon.

**Comment by kardianos** [comment] 2016-11-23 17:55
I just installed ms sql server on my linux laptop to make this easier for me to test. I fixed the test so it compiles, but I haven't yet filled out the actual methods required. I'll work on this more in a bit.

**Comment by kardianos** [comment] 2016-11-25 20:42
Multiple result sets is in the branch.

I'd like to also support the other features too.

**Comment by denisenkom** [comment] 2016-11-26 03:56
Looking good!  Lets split work between us if you want to continue to work.  I can take "Support for query column type information".

I am also trying to merge nextresultset-denisenk branch into master but it is failing build on go 1.7 as is expected.  I tried adding "// +build go1.8" directive to make go 1.7 to ignore this test but "go test" seems to ignore this directive and still tries to run this test.  Do you know how this can be achieved?

**Comment by kardianos** [comment] 2016-11-26 06:39
Oh, good point. I'll make this backwards compatible for tests. Thanks.

**Comment by denisenkom** [comment] 2016-11-28 01:40
I finished implementation for column introspection: https://github.com/denisenkom/go-mssqldb/tree/column-types-denisenk

**Comment by denisenkom** [comment] 2016-11-28 01:42
Next I will work on "transaction isolation levels"

**Comment by denisenkom** [comment] 2016-11-28 04:31
Looks like I would need to implement Context first, so I will start working on it instead of "transaction isolation levels"

**Comment by kardianos** [comment] 2016-11-28 18:14
The multiple result set branch should be ready to merge now. It builds and tests with go1.7 and go1.8.

**Comment by kardianos** [comment] 2016-11-28 18:23
The column-type branch LGTM

**Comment by kardianos** [comment] 2016-11-28 18:25
The context branch looks good to me so far.

**Comment by denisenkom** [comment] 2016-12-04 16:44
context methods are implemented

**Comment by denisenkom** [comment] 2016-12-04 16:44
transaction isolation levels are implemented

**Comment by denisenkom** [comment] 2016-12-04 16:45
Will do named parameters next

**Comment by kardianos** [comment] 2016-12-04 16:55
When implementing named parameters, all parameter names will come in without a symbol "@". Need to prefix with "@" before sending.

**Comment by denisenkom** [comment] 2016-12-04 18:14
CR for named parameters: https://github.com/denisenkom/go-mssqldb/pull/188

**Comment by denisenkom** [comment] 2016-12-04 18:17
I will look into cancelable queries next

**Comment by denisenkom** [comment] 2016-12-05 03:12
Is there a good way to use Context with sockets?  E.g. propagate context cancellation and deadlines to sockets?

**Comment by denisenkom** [comment] 2016-12-06 04:17
Looks like all features are implemented.  I will add more tests and then close it.  Thanks for help Daniel!

**Closed** 2016-12-08 04:03 UTC
