### ISSUE TITLE
Improper parsing of string identifiers

### ISSUE THREAD

**Issue by lcaballero** [denisenkom/go-mssqldb#170] opened 2016-09-21 20:46 UTC
I think [#169](https://github.com/denisenkom/go-mssqldb/issues/169) needs to be re-opened.  The parsing in the library won't handle the following:

`User Id={ abc ;}`

Where the `;` is part of the value.  Mainly because of the split in this line: [tds.go@25](https://github.com/denisenkom/go-mssqldb/blob/master/tds.go#L25)

**Comment by denisenkom** [comment] 2016-11-26 18:11
Duplicate of #169

**Closed by denisenkom** 2016-11-26 18:11 UTC
