### ISSUE TITLE
"bad connection" is too generic an error to be useful?

### ISSUE THREAD

**Issue by jbwiv** [denisenkom/go-mssqldb#275] opened 2017-06-26 18:06 UTC
Guys,

Thanks for your work on this driver first and foremost. It's been very useful.
I hit a problem today where I had a query which was running longer than the 30 second default would allow. The behavior I observed in the driver seems to be to give up, print "BeginRead failed driver: bad connection", and then retry two more times before giving up completely.

It took me a decent amount of time to track down what was happening, where if there had been a more descriptive error message (something like "execution time exceeded configured time of %v seconds") it would have been much easier to understand.

My intent is not to say that your error handling is crappy. However, I'm relatively new to Go...naively it would seem a better message would be possible. Is there something practically preventing this from happening, or is this a good example of an improvement you'd be interested in getting a pull request for?

Thanks,
John

**Comment by kardianos** [comment] 2017-06-26 18:23
This is a valid issue. We don't have a great story for handling error messages in a good way.
Feel free to send a PR, would need to try to determine why the connection was canceled.

**Comment by dimdin** [comment] 2017-06-26 18:35
The driver detects the timeout but returns driver.ErrBadConn to signal that the connection is not longer valid.
Instead of returning ErrBadConn, we can close the connection (mark it as invalid) and return the actual error. If a invalid connection is reused then we can return ErrBadConn.
This solves the incorrect error reporting and allows the driver connection to be recycled later.

**Comment by captncraig** [comment] 2017-06-27 21:00
One issue I see with that solution @dimdin is that you get an error on the next operation you do on the db, that we could prevent by opening a new connection instead of reusing a bad one. Since the pooling is not managed by the driver, it feels kinda odd.

**Comment by mikewilliamson** [comment] 2017-06-28 17:52
My first inclination was to agree with @captncraig.  I don't think the implementation of connection pooling in the SQL library is particularly well done, but it does feel a bit wrong to not immediately return ErrBadConn, thus leaving the bad connection lingering in the pool.

However, after looking at the way that the library manages the pool, I don't think you actually would get errors on for the next operation.  I mean, the library would get an ErrBadConn from the driver, but then it would always try again with another connection from the pool (or make a new one).   

So @dimdin's proposal could work really well.  It would certainly be nice for applications to get a better error message, and to get them sooner.  As @jbwiv observed, the current approach will always re-try long-running queries 3 times (twice with existing connections, and once with a new one), because the driver is conflating an i/o timeout as being a bad connection.  In fact, maybe this was the intended behaviour for drivers?

P.S.  I second @jbwiv's note of thanks for the work on this driver.  We depend on it heavily for business-critical applications.  If any of the contributors are ever passing through London, there's a round of drinks on me!

**Comment by denisenkom** [comment] 2017-07-17 02:58
@dimdin proposal would probably work in most cases but it would break in some.

Suppose you run three queries and those queries timeout, this would cause connection pool to contain three connections in a bad state.
Now you run another query, this query will pick one connection from pool but such connection would be bad, so it returns ErrBadConn.  This will cause sql library to remove bad connection from pool, but three are still two connections left.  Now it will try again and again, and will give up after third attempt returning ErrBadConn to user.

I think sql library should be updated to allow drivers to tell connection state good or bad independently of error message.  And allow driver to specify when query can be retried and when it should not be retried.

**Comment by mikewilliamson** [comment] 2017-07-18 12:49
I agree that the interface between the SQL library and the driver could be much better, but I don't think it would actually fail as you describe.  It will only try twice with connections from the pool, and if they are both ErrBadConn then the third time it will try with a new connection.

https://golang.org/src/database/sql/sql.go?s=32487:32584

At least that's how it works with standard queries and execs.  Things get a little murkier with prepared statements.  This code all seems unnecessarily contorted because of the deficiency in the driver interface.

**Comment by denisenkom** [comment] 2017-07-19 02:35
Yeah, looks like it would work.  I will look into implementing this.

**Comment by kardianos** [comment] 2018-10-27 05:37
Error handling is better now with newer go and newer driver. Closing this issue for now.

**Closed by kardianos** 2018-10-27 05:37 UTC
